# added this by Blaise based on (https://lists.riot-os.org/pipermail/users/2015-November/000468.html)
ifneq (,$(filter cc110x,$(USEMODULE)))
    DISABLE_MODULE += gnrc_sixlowpan_iphc
endif
ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  #USEMODULE += saul_bme280
endif
